#! /usr/bin/bash

flatpak run org.flatpak.Builder \
--force-clean \
--sandbox \
--user \
--install \
--install-deps-from=flathub \
--ccache \
--mirror-screenshots-url=https://dl.flathub.org/media/ \
--repo=.work-dir/repo .work-dir/builddir \
io.github.qcanvas.QCanvasApp.yaml
